# Documentation: https://roots.io/trellis/docs/ssh-keys/
admin_user: azureuser

# Also define 'vault_users' (`group_vars/staging/vault.yml`, `group_vars/production/vault.yml`)
users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
      - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMbi6n3z/5GKqG7Ih/BUJf1i7NyTc8aPR3h1x+39teDsB89QDgTrxfagexaAxuhXbRgw+ai6yE6iAOB6FRPKUjY= Awakening-Web-Server@secretive.sabrina.local"
      - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOSOJLmptQmuOTp+xKVvqaWcU1EgkMS6Df6YQQ3Yw6uSgeF2DSyPLuHJBO4qbF9pgFbxjdjrzs7Tiyh3XX+bZbQ= Awakening-Web-Server@secretive.Izzi.local"
      # - https://github.com/username.keys
  - name: "{{ admin_user }}"
    groups:
      - sudo
    keys:
      - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMbi6n3z/5GKqG7Ih/BUJf1i7NyTc8aPR3h1x+39teDsB89QDgTrxfagexaAxuhXbRgw+ai6yE6iAOB6FRPKUjY= Awakening-Web-Server@secretive.sabrina.local"
      - "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOSOJLmptQmuOTp+xKVvqaWcU1EgkMS6Df6YQQ3Yw6uSgeF2DSyPLuHJBO4qbF9pgFbxjdjrzs7Tiyh3XX+bZbQ= Awakening-Web-Server@secretive.Izzi.local"
      # - https://github.com/username.keys

web_user: web
web_group: www-data
web_sudoers:
  - "/usr/sbin/service php7.4-fpm *"
