---
- name: Create web root of sites
  file:
    path: "{{ www_root }}/{{ item.key }}/{{ item.value.current_path | default('current') }}/web"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0755'
    state: directory
  with_dict: "{{ wordpress_sites }}"

- name: Create shared folder of sites
  file:
    path: "{{ www_root }}/{{ item.key }}/shared"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0755'
    state: directory
  with_dict: "{{ wordpress_sites }}"

- name: Change site owner to user
  file:
    path: "{{ www_root }}/{{ item.key }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: '0755'
    state: directory
    recurse: yes
  with_dict: "{{ wordpress_sites }}"
  # Disabled because of issues provisioning on Lima.
  # See: https://github.com/roots/trellis/commit/514b7943cd199d08622b2ded63f3e5a1f3a21414
  when: false
